RVA_020: Provide additional context for Ssccfg
riscv-non-isa/riscv-server-platform pull request #21
Opened 2024-07-29 11:56 UTC by punitagrawal

The privileged specification includes a chapter about "Smcdeleg" Counter Delegation Extension, Version 1.0.0 that includes the description of Smcdeleg and Ssccfg.

For clarity / ease of finding the the details, update the RVA_020 requirement to include a reference to Smcdeleg.

Closes: #19

2024-07-30 02:19 UTC, ved-rivos commented
This was intentional. The Platform specification is written to provide the requirements that the privilege levels less than M can expect. We have not placed any mandates on the M-mode ISA in the Server Platform or the Server SoC specification. I notice we have Smcntrpmf which I think should also be removed.

2024-07-30 02:19 UTC, ved-rivos requested changes
The smcdeleg and smcntrpmf should be remove from the list.

2024-08-05 15:46 UTC, punitagrawal commented
@ved-rivos Thank you for taking a look.

The reason for adding `smcdeleg` was that there is confusion about `ssccfg` - folks have complained about not being able to find its description. Even the chapter describing it only includes `smcdeleg`. I've seen `ssccfg` being incorrectly referred to in many places as `sscfg` (one example[0]) which obviously then makes it even harder to find. 

I just had a look to confirm the content of `smcntrpmf` - it seems to be implied if `smcdeleg/ssccfg` is implemented. So dropping it should be ok. Though I hope this indirect requirement doesn't get missed by any implementation.

For my learning - I was wondering what is the rationale for the platform specification targeting privilege levels less than M. Is there a downside to having M mode extensions also in the list?

2024-08-05 16:01 UTC, ved-rivos commented
> For my learning - I was wondering what is the rationale for the platform specification targeting privilege levels less than M. Is there a downside to having M mode extensions also in the list?

The RVA profiles, server SoC specification, and the server platform specification are written to specify requirements as perceived by the S-mode and lower. This is to ensure we can support a single binary OS distribution on compliant platforms. An implementation that claims support Ssccfg should provide that extension as perceived by the S-mode. We are presently not placing mandates on the M-mode ISA - in fact none of these specifications even require the M-mode ISA to be implemented - for instance the machine mode may be an emulator.

2024-08-05 16:17 UTC, punitagrawal commented
> The smcdeleg and smcntrpmf should be remove from the list.

I've pushed an updated patch doing this.

2024-08-05 16:20 UTC, ved-rivos approved these changes

2024-08-31 02:19 UTC, merged